//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Savea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int Id { get; set; }
        public Nullable<int> Forma_id { get; set; }
        public Nullable<int> Pregunta_id { get; set; }
        public string Usuario_id { get; set; }
        public Nullable<int> Resultado { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Forma Forma { get; set; }
    }
}
